# Generated by Django 5.2.17 on 2026-09-08 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultationnote',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-created_at']},
        ),
    ]
