# Generated by Django 5.2.17 on 2026-09-12 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_consultationnote_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='teleconsult',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='teleconsult_link',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmada'), ('CHECKED_IN', 'Ingresó (check-in)'), ('COMPLETED', 'Atendida'), ('CANCELLED', 'Cancelada'), ('NO_SHOW', 'No asistió')], default='PENDING', max_length=16),
        ),
        migrations.CreateModel(
            name='ClinicalExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('LABORATORY', 'Laboratorio clínico'), ('IMAGING', 'Imágenes diagnósticas'), ('OTHER', 'Otro')], default='LABORATORY', max_length=16)),
                ('name', models.CharField(max_length=200)),
                ('result', models.TextField(blank=True, default='')),
                ('reference_range', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'En proceso'), ('COMPLETED', 'Completado')], default='PENDING', max_length=16)),
                ('performed_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='appointments.appointment')),
            ],
            options={
                'db_table': 'appointments_clinicalexam',
                'ordering': ['-created_at'],
            },
        ),
    ]
