# Generated by Django 5.2.17 on 2026-09-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('module', models.CharField(max_length=64)),
                ('method', models.CharField(max_length=8)),
                ('path', models.CharField(max_length=255)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_auditlog',
                'ordering': ['-created_at'],
            },
        ),
    ]
