# Generated by Django 5.2.17 on 2026-09-12 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0003_alter_doctorprofile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('area', models.CharField(blank=True, default='', max_length=120)),
                ('floor', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('FREE', 'Disponible'), ('IN_USE', 'En uso'), ('MAINTENANCE', 'Mantenimiento'), ('DISINFECTION', 'Desinfección')], default='FREE', max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boxes', to='doctors.doctorprofile')),
            ],
            options={
                'db_table': 'boxes_box',
                'ordering': ['code'],
            },
        ),
    ]
