# Generated by Django 5.2.17 on 2026-09-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(blank=True, default='', max_length=32)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], default='', max_length=1)),
                ('blood_type', models.CharField(blank=True, default='', max_length=8)),
                ('medical_history', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'patients_patientprofile',
            },
        ),
    ]
