# Generated by Django 5.2.17 on 2026-09-12 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='finances.insurance'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='policy_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
