# Generated by Django 5.2.17 on 2026-09-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('color', models.CharField(blank=True, default='', max_length=16)),
                ('icon', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'specialties_specialty',
                'ordering': ['name'],
            },
        ),
    ]
