# Generated by Django 5.2.17 on 2026-09-08 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Disponible'), ('BLOCKED', 'Bloqueado'), ('PAST', 'Pasado')], default='ACTIVE', max_length=16)),
                ('box', models.CharField(blank=True, default='', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='doctors.doctorprofile')),
            ],
            options={
                'db_table': 'schedules_availability',
                'ordering': ['date', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('doctor', 'date'), name='schedules_doctor_date_unique'), models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='schedules_time_range_valid')],
            },
        ),
    ]
