# Generated by Django 5.2.17 on 2026-09-08 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specialties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=64, unique=True)),
                ('box', models.CharField(blank=True, default='', max_length=16)),
                ('available', models.BooleanField(default=True)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='specialties.specialty')),
            ],
            options={
                'db_table': 'doctors_doctorprofile',
            },
        ),
    ]
