# Generated by Django 5.2.17 on 2026-09-08 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorprofile',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
    ]
